apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
  - name: EventRateLimit
    path: /etc/kubernetes/addons/event-rate-limit.yaml
  - name: ImagePolicyWebhook
    configuration:
      imagePolicy:
        kubeConfigFile: /var/lib/minikube/certs/kube-image-bouncer.yml
        allowTTL: 50
        denyTTL: 50
        retryBackoff: 500
        defaultAllow: true
