apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority: /var/lib/minikube/certs/ca.crt
      server: https://192.168.64.1:1323/image_policy
    name: bouncer_webhook
contexts:
  - context:
      cluster: bouncer_webhook
      user: api-server
    name: bouncer_validator
current-context: bouncer_validator
preferences: {}
users:
  - name: api-server
    user:
      client-certificate: /var/lib/minikube/certs/apiserver.crt
      client-key: /var/lib/minikube/certs/apiserver.key
